name: sporg
description: "A Flutter application for event attendance tracking using QR codes in SPOT unit in FMTU."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0
  mobile_scanner: ^5.0.0
  provider: ^6.0.0
  http: ^1.1.0
  # للتاريخ وتنسيقه
  intl: ^0.18.0
  # لإنشاء ملفات CSV (اكسيل)
  csv: ^5.0.0
  path_provider: ^2.0.15
  # لمشاركة الملف الناتج
  share_plus: ^7.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.7
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true

assets:
  - assets/sporg-logo.png
